services:
  - type: web
    name: pubmed-search
    env: python
    plan: free
    buildCommand: pip install -r pubmed_search/requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT pubmed_search.app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        value: 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
      - key: PUBMED_API_KEY
        value: b6a22ac9a183cabddf8a38046641c2378308
      - key: DATABASE_PATH
        value: /tmp/pubmed_search_history.db

